---
title: "Species richness and evenness calculations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load tidyverse first
library(tidyverse)
library(vegan)
library(ggpubr)
library(gridExtra)
library(grid)
library("coin")
library(ggpubr)
library(rstatix)
```

#Load mOTU counts table
```{r }
count_table<-read.csv("data/mOTU_counts.tsv", sep = '\t', row.names=1)
```

#filter counts table
```{r}
# remove -1 (unclassified) line
count_table <- count_table[setdiff(rownames(count_table), "-1"), ]

#remove species that never occurr across all samples
count_table_filtered <- count_table[rowSums(count_table) > 0, ]
count_table_filtered_t<-data.frame(t(count_table_filtered))
```

#load metadata table (after timeseries dereplication)
```{r}
meta.data<-read.csv("data/metadata_timeseries_dereplicated.csv", sep = ',', stringsAsFactors=F)
rownames(meta.data) <- as.character(meta.data$Samples)
```

#Calculate alpha diversity
```{r }
filename1 <- "alpha_diversity.R"
filename2 <- "rarefaction.R"

#download R scripts sourced if they are not already present
if ((!file.exists(filename1)) | (!file.exists(filename2))) {
  dir.create(path = "external_scripts")
  download.file(url = "https://raw.githubusercontent.com/defleury/Toolbox_16S/master/R/function.alpha_diversity.R", destfile = "external_scripts/alpha_diversity.R")
  download.file(url = "https://raw.githubusercontent.com/defleury/Toolbox_16S/master/R/function.rarefaction.R", destfile = "external_scripts/rarefaction.R")
}

source("external_scripts/alpha_diversity.R")
source("external_scripts/rarefaction.R")

#get as R object the alpha diversity results of already computed. 
filename <- "data/alpha_diversity/HillDiv_counts_withMetadata.rds"

if (file.exists(filename)) {
  alpha.frame.m <- readRDS(file = filename)
} else {
    
  #Calculate rarefied alpha diversities
  #alpha div measures are replaced by NA for undersampled samples (see script)
  alpha.frame <- Hill_Diversity.rarefied(
    count_table_filtered, 
    size=100, # min 100 reads per sample
    iterations=100, 
    q.H=c(0, 1, 2) #Hill's numbers
    )
  
  colnames(alpha.frame) = c("Sample", "Richness", "exp_Shannon", "inv_Simpson") 
  #calculate evenness as exp(Shannon)/Richness
  alpha.frame[, "evenness (q1)"] <- alpha.frame$exp_Shannon/ alpha.frame$Richness
  colnames(alpha.frame) = c("Sample", "Richness", "exp_Shannon", "inv_Simpson", "evenness") 
  
  alpha.frame <- alpha.frame[-c(6)]
  rownames(alpha.frame) <- as.character(alpha.frame$Sample)
  
  #Append metadata to alpha diversity results table
  alpha.frame.m <- cbind(meta.data, alpha.frame[rownames(meta.data), ])

  #save as rds object the result of the alpha diversity calculation
  saveRDS(alpha.frame.m, file = filename)
}
```

#remove NA from alpha div values (from undersampled samples)
```{r}
alpha.frame.m <- alpha.frame.m %>% 
  filter(is.na(Richness)==FALSE)
```

#function to count number of samples per each boxplot
```{r}
stat_box_data <- function(y) {
  return(data.frame(y = 0, label = paste(length(y))))
}
```

#define color palette and text size
```{r}
size_text = 10
age_colors <- c("#01579B", "#F9A825")
```

#calculate rarefied species richness across CDI, D-Ctr and H-Ctr samples
```{r}
#calculate categories
colors_2series <- c("darkred", "darkred",'#BDBDBD', "#424242")

metadata_file_CDI_controls <- meta.data %>%
    filter(Host=="Human" & Environment=="Gut" & Gut_sample_type=="Stool" & final_representative=="Yes" & Status != "NA") %>% 
  group_by(Study) %>% 
  dplyr::mutate(atLeastTwoPosCDI = (sum(CDI=="Yes")>1) | (sum(subject_disease_status=="CDI")>1)) %>% 
  #selected studies to filter out due to their study design or non-CDI samples
  dplyr::filter(atLeastTwoPosCDI == TRUE & Study != "Draper_2018_FMT_phage" & Study != "Kao_2017_FMT" & subject_disease_status != "UC")

#identify CDI samples
CDI_CdiffPos <- metadata_file_CDI_controls %>% 
  filter((subject_disease_status == "CDI" & Status == "Diseased" & Cdiff=="Yes") | (subject_disease_status == "Diarrhoea" & CDI == "Yes" & Status == "Diseased" & Cdiff=="Yes")) %>% 
  mutate(group = "CDI_CdiffPos")

CDI_CdiffNeg <- metadata_file_CDI_controls %>% 
  filter((subject_disease_status == "CDI" & Status == "Diseased" & Cdiff=="No") | (subject_disease_status == "Diarrhoea" & CDI == "Yes" & Status == "Diseased" & Cdiff=="No")) %>% 
  mutate(group = "CDI_CdiffNeg")

#identify CONTROL samples

## diseased controls (D-Ctr)
DCtr_CdiffPos <- metadata_file_CDI_controls %>% 
  filter(
    #diseased subjects without CDI not diarrhea
    (subject_disease_status != "CDI" & subject_disease_status != "CTR" & subject_disease_status != "Diarrhea" & CDI == "No" & Status == "Diseased" & Cdiff=="Yes") |
    #diseased subjects without CDI but with diarrhea
    (subject_disease_status == "Diarrhea" & CDI == "No" & Status == "Diseased"  & Cdiff=="Yes")) %>% 
  mutate(group = "DCtr_CdiffPos")

DCtr_CdiffNeg <- metadata_file_CDI_controls %>% 
  filter(
    #diseased subjects without CDI not diarrhea
    (subject_disease_status != "CDI" & subject_disease_status != "CTR" & subject_disease_status != "Diarrhea" & CDI == "No" & Status == "Diseased" & Cdiff=="No") |
    #diseased subjects without CDI but with diarrhea
    (subject_disease_status == "Diarrhea" & CDI == "No" & Status == "Diseased"  & Cdiff=="No")) %>% 
  mutate(group = "DCtr_CdiffNeg")

## healthy controls (H-Ctr)
HCtr_CdiffPos <- metadata_file_CDI_controls %>% 
  filter(subject_disease_status == "CTR" & CDI == "No" & Status == "Healthy" & Cdiff=="Yes") %>% 
  mutate(group = "HCtr_CdiffPos")

HCtr_CdiffNeg <- metadata_file_CDI_controls %>% 
  filter(subject_disease_status == "CTR" & CDI == "No" & Status == "Healthy" & Cdiff=="No") %>% 
  mutate(group = "HCtr_CdiffNeg")

#Combine and save CDI, D-Ctr and H-Ctr samples
all_merged <- rbind(CDI_CdiffNeg, CDI_CdiffPos, DCtr_CdiffNeg, DCtr_CdiffPos, HCtr_CdiffNeg, HCtr_CdiffPos) 

group.to.keep <- all_merged %>% 
  group_by(group) %>% 
  dplyr::summarise(n=dplyr::n())%>% 
  filter(n>=5) %>% 
  pull(group)

all_merged <- all_merged %>% 
  ungroup() %>% 
  select(Samples, group) %>% 
  filter(group %in% group.to.keep)

all_merged.alpha.frame.m <- left_join(all_merged, rownames_to_column(alpha.frame.m), by = c("Samples" = "rowname"))

all_merged.alpha.frame.m$group <- as.factor(all_merged.alpha.frame.m$group)
all_merged.alpha.frame.m <- all_merged.alpha.frame.m %>% 
  mutate(group=fct_relevel(group, "CDI_CdiffPos","CDI_CdiffNeg","DCtr_CdiffNeg","HCtr_CdiffNeg"))
  
my_comparisons <- list(c("CDI_CdiffPos", "DCtr_CdiffNeg"), 
  c("CDI_CdiffPos", "HCtr_CdiffNeg"), 
  c("CDI_CdiffNeg", "DCtr_CdiffNeg"), 
  c("CDI_CdiffNeg", "HCtr_CdiffNeg"), 
  c("DCtr_CdiffNeg", "HCtr_CdiffNeg")) 

stat.test <- compare_means(Richness ~ group, data = all_merged.alpha.frame.m, method = "t.test")

pCDI_cdiff<- ggplot(data = all_merged.alpha.frame.m, mapping = aes(x = group, y = Richness, fill=group)) +
    geom_boxplot(outlier.size = -1) +
    scale_fill_manual(values=colors_2series) +
    theme_bw() +
    theme(plot.title = element_text(family = "Helvetica", face = "bold", size = (10)), 
          axis.text.x = element_text(angle=45, vjust=1.0, hjust = 1.0, size = 10), 
          strip.background = element_rect(color="white", fill="white")) +
    stat_summary(fun.data = stat_box_data, geom = "text", fun = median, position = position_dodge(width = 0.85), size=3, angle = 0)

pCDI_cdiff <- pCDI_cdiff + stat_compare_means(comparisons = my_comparisons, label = "p.signif", method = "wilcox.test") 

#plot
pdf(file="figures/CDI/CDI_richness.pdf", width=5, height=5)
grid.arrange(pCDI_cdiff, ncol = 1)
dev.off()
```

